Added contribution guride
StefanIvemo/BicepPowerShell pull request #118
Opened 2021-04-13 07:32 UTC by StefanIvemo

- Created a CONTRIBUTING.md
- Updated the contributing section in README.md

Closes #117

2021-04-14 16:35 UTC, matsest commented on CONTRIBUTING.md
> +Update-MarkdownHelp .\docs
Suggestion to make it more inline with the previous paragraph:

```suggestion
# re-import your module with latest changes
Import-Module .\Bicep.psd1 -Force
Update-MarkdownHelp .\Docs\Help
```

2021-04-16 09:03 UTC, SimonWahlin requested changes

2021-04-16 09:03 UTC, SimonWahlin commented on CONTRIBUTING.md
> +Import-Module .\Bicep.psd1 -Force
Path should be .\Source\Bicep.psd1

2021-04-16 09:04 UTC, StefanIvemo commented on CONTRIBUTING.md
> +- Run the script `.\scripts\downloadDependencies.ps1` to download the required dependencies (Bicep Assemblies (DLLs) and Bicep Types information) to the Assets (`Source/Assets`) folder.
I will add that!

2021-04-17 18:25 UTC, SimonWahlin approved these changes

2021-04-17 18:31 UTC, merged